### ISSUE TITLE
Overcomplicated?

### ISSUE THREAD

**Issue by doublep** [jcs090218/setup-emacs#106]
According to the documentation, this action is basically "use either `purcell/setup-emacs` or `jcs090218/setup-emacs-windows`" depending on the OS. But it appears to be very complicated using JS and with some 20 dependencies... Is there any reason for that, e.g. inlining `setup-emacs-windows`?

**Comment by jcs090218** [comment]
The goal of this action is to install Emacs across modern OSs (Linux, Mac OS, and Windows). This action is generated through a template, and it has those dependencies by default. I assumed those are necessary for GitHub actions to run, but I was wrong. Nevertheless, windows layer are written in typescript, so that's how I got those dependencies. Technically, I think we can write those in batches but I'm not 100% sure. 🤔 

The action is built this way due to historical reasons. At first, I was trying to make `setup-emacs-windows` and never thought about merging `purcell/setup-emacs`. At some point (after a few years), I realized I could just merge the two actions and it will be so much easier. That's it! I didn't bother to change the source code since it's still working. 

Is this overcomplicated? Yes, there is space to improve it. But like I said, I don't bother changing it since it's working. However, feel free to discuss possible improvements! Who will blame better source code!? 😁

**Comment by doublep** [comment]
> The goal of this action is to install Emacs across modern OSs (Linux, Mac OS, and Windows).

Yes, that's why I started using it in my workflows in place of Purcell's one or instead of two conditioned actions, just as described in your `README.md`. However, it seems my workflows have become somewhat slower as a result, because now they install Node.js and what not that I normally don't use.

However, I'm pretty sure you could just replace `runs` block in your `action.yml` like this (untested):

    runs:
      using: composite
      steps:

      - if: runner.os != 'Windows'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ inputs.version }}
      - if: runner.os == 'Windows'
        uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ inputs.version }}

and drop all JS bits. This would greatly simplify the action and remove the dependency on Node.js — which, of course, could still be pulled later on, but not everyone needs it for Elisp-oriented workflows.

**Comment by jcs090218** [comment]
Oh, yes! You are right. 🤔 I wasn't aware of this, would you like to open a PR for this?
